export const tagColors: Record<string, string> = {
  "Historical Fiction": "cyan",
  Mystery: "magenta",
  Thriller: "red",
  "Science Fiction": "blue",
  Fantasy: "purple",
  Romance: "pink",
  Horror: "geekblue",
  "Literary Fiction": "orange",
  Biography: "green",
  "Self-Help": "lime",
  "True Crime": "gold",
  Travel: "volcano",
  Cookbooks: "geekblue",
  History: "orange",
  Science: "cyan",
  Politics: "blue",
  Classics: "pink",
  Contemporary: "purple",
  Dystopian: "red",
  "Young Adult": "magenta",
  "Children's": "lime",
  "Graphic Novels": "gold",
  Poetry: "geekblue",
  Humor: "cyan",
  Adventure: "orange",
  Sports: "volcano",
  Gardening: "green",
  Art: "purple",
  Music: "blue",
  Photography: "magenta",
  Religion: "cyan",
  Philosophy: "geekblue",
};
