export const tags = {
  fiction: [
    "Historical Fiction",
    "Mystery",
    "Thriller",
    "Science Fiction",
    "Fantasy",
    "Romance",
    "Horror",
    "Literary Fiction",
  ],
  nonFiction: [
    "Biography",
    "Self-Help",
    "True Crime",
    "Travel",
    "Cookbooks",
    "History",
    "Science",
    "Politics",
  ],
  genres: [
    "Classics",
    "Contemporary",
    "Dystopian",
    "Young Adult",
    "Children's",
    "Graphic Novels",
    "Poetry",
    "Humor",
    "Adventure",
  ],
  specialInterests: [
    "Cookbooks",
    "Travel",
    "Sports",
    "Gardening",
    "Art",
    "Music",
    "Photography",
    "Religion",
    "Philosophy",
  ],
};
