export const categories = [
  "Historical Fiction",
  "Mystery",
  "Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Horror",
  "Literary Fiction",
  "Biography",
  "Self-Help",
  "True Crime",
  "Travel",
  "Cookbooks",
  "History",
  "Science",
  "Politics",
  "Classics",
  "Contemporary",
  "Dystopian",
  "Young Adult",
  "Children's",
  "Graphic Novels",
  "Poetry",
  "Humor",
  "Adventure",
  "Sports",
  "Gardening",
  "Art",
  "Music",
  "Photography",
  "Religion",
  "Philosophy",
];
